_extends: github-apps-config-next

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - "license/snyk (Customer Products)"
          - "license/snyk (financial times)"
          - "security/snyk (Customer Products)"
          - "security/snyk (financial times)"
      enforce_admins: false
      restrictions:
        users: []
        teams: []
  - name: version-*
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - "license/snyk (Customer Products)"
          - "license/snyk (financial times)"
          - "security/snyk (Customer Products)"
          - "security/snyk (financial times)"
      enforce_admins: false
      restrictions:
        users: []
        teams: []
